### ISSUE TITLE
Python 2 compatibility: division

### ISSUE THREAD

**Issue by rcfox** [Twista/python-polylabel#1]
Hi, thanks for this library!

I needed to use it in Python 2.7. It was mostly trivial to convert, but the one tricky part was the division.

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 / 2
0.5

$ python2
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 / 2
0
```

It's just a matter of making sure that you're always dividing by a float. Otherwise, the resulting point won't be in the correct place. (I had a triangle, and it was returning a point on one of the edges!)

I was too lazy to make a proper pull request, so I'm leaving this issue for anyone else who wants to use this code in Python 2. (And an issue seems like it might be more visible than a pull request in case this gets ignored.)

**Comment by Twista** [comment]
great catch. thanks for note, will adjust code soon

**Comment by Twista** [comment]
thanks again. the code is now python2 compatible :)
