### ISSUE TITLE
add returning distance to a polygon

### ISSUE THREAD

**Issue by cvlal9ol** [Twista/python-polylabel#2]
Hi,
thank you for developing this useful tool.
Could you, please, add an option to get the best_cell.d (distance to the current polygon) as an output value with center's coordinates? (I'm about the function `polylabel`)

**Comment by Twista** [comment]
Hey,

thanks! gonna take a look later today. Afaik it shouldn't be problem at all :)

**Comment by Twista** [comment]
Hey @al9ol 

just published new version on pypi - https://pypi.org/project/python-polylabel/#history

usage:
```python
polylabel(data, with_distance=True)
```
